type: systemd
system:
  enabled:
  #  - tailscaled.service # Enabled (runs on system boot)
    - com.system76.Scheduler.service
    - libvirtd.service
  disabled:
    # Disabled (does not run on system boot, unless other unit strictly requires it)
  masked:
    # Masked (does not run on system boot, under any circumstances)
  unmasked:
    # Unmasked (runs on system boot, even if previously masked)
user:
  enabled:
    # Enabled (runs for the user)
  disabled:
    # Disabled (does not run for the user, unless other unit strictly requires it)
  masked:
    # Masked (does not run for the user, under any circumstances)
  unmasked:
    # Unmasked (runs for the user, even if previously masked)
